/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.ubc.gpec.ia.analyzer.gui;

import ca.ubc.gpec.ia.analyzer.controller.SettingsEditor;
import ca.ubc.gpec.ia.analyzer.controller.StainAnalyzerController;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.JTabbedPane;

/**
 *
 * @author samuelc
 */
public class MainJPanel extends javax.swing.JPanel {

    private StainAnalyzerController stainAnalyzerController;

    /**
     * Creates new form MainJPanel
     */
    public MainJPanel() {
        initComponents();
        // DO NOT DO ... new configJPanel2() !!! ... this is done in initComponents()
    }

    /**
     * set settingsEditor
     *
     * @param settingsEditor
     */
    public void setSettingsEditor(SettingsEditor settingsEditor) {
        configJPanel.setSettingsEditor(settingsEditor);
    }

    /**
     * set stainAnalyzerController ... make the connection!!! 1. configJPanel
     * <-> stainAnalyzerController 2. imageSelectionJPanel <->
     *
     * @param stainAnalyzerController stainAnalyzerController
     */
    public void setStainAnalyzerController(StainAnalyzerController stainAnalyzerController) {
        this.stainAnalyzerController = stainAnalyzerController;
        configJPanel.setStainAnalyzerController(stainAnalyzerController);
        stainAnalyzerController.setImageSelectionJPanel(imageSelectionJPanel);
        stainAnalyzerController.setMainJPanel(this);
        stainAnalyzerController.setConfigJPanel(configJPanel);
    }

    public JTabbedPane getMainJTabbedPane() {
        return mainTabbedPane;
    }

    /**
     * override paint
     *
     * @param g
     */
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        // TODO: hard code for now need to change to support window resize!!!
        imageSelectionJPanel.setPreferredSize(new Dimension(400, 300));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        configJPanel = new ca.ubc.gpec.ia.analyzer.gui.ConfigJPanel();
        mainTabbedPane = new javax.swing.JTabbedPane();
        imageSelectionJPanel = new ca.ubc.gpec.ia.analyzer.gui.ImageSelectionJPanel();
        analyzeButton = new javax.swing.JButton();

        configJPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mainTabbedPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        imageSelectionJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainTabbedPane.addTab("Original image(s)", imageSelectionJPanel);

        analyzeButton.setText("analyze");
        analyzeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                analyzeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(configJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(analyzeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(configJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainTabbedPane)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(analyzeButton)))
                .addContainerGap())
        );

        mainTabbedPane.getAccessibleContext().setAccessibleName("imageSelectionTab");
        mainTabbedPane.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void analyzeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_analyzeButtonMouseClicked
        try {
            stainAnalyzerController.analyzeIao(imageSelectionJPanel.getSelectedIAOs().first());
        } catch (Exception e) {
            // TODO: need to do something!!!
        }
    }//GEN-LAST:event_analyzeButtonMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analyzeButton;
    private ca.ubc.gpec.ia.analyzer.gui.ConfigJPanel configJPanel;
    private ca.ubc.gpec.ia.analyzer.gui.ImageSelectionJPanel imageSelectionJPanel;
    private javax.swing.JTabbedPane mainTabbedPane;
    // End of variables declaration//GEN-END:variables
}
